#! /bin/bash

# This handles cleanup operations and boiler-plate code and it is executed after downloading a copy of the latest release.
#
# Since the version of the script executed is the version included in the release, it is safe to change between releases.
rm -R src 2>/dev/null
rm -R docs 2>/dev/null
rm -R tests 2>/dev/null
rm -R scripts/new 2>/dev/null
rm Doxyfile 2>/dev/null
rm CMakeLists.txt 2>/dev/null
rm *.md 2>/dev/null
rm LICENSE 2>/dev/null
rm NOTICE 2>/dev/null
mv ./examples/boiler_plate/* ./
rm -R ./examples/boiler_plate  2>/dev/null

